### ISSUE TITLE
Does not work with Android

### ISSUE THREAD

**Issue by L2jLiga** [blake/external-mdns#10]
Hi there, I'm trying to make this work with Android phones with no success

I've tried original image, image with this commits: #9 as well as adding more "fixes" like setting `RecursionDesired` bit to 0 accroding to https://datatracker.ietf.org/doc/html/rfc6762#section-18.6.

mDNS works perfectly fine on other machines in my network - Ubuntu, Fedora, Windows 10, Windows 11
I've tested it on 2 phones:
- Xiaomi Poco X3 with PixelExperience Plus 13
- Xiaomi Mi 9T with latest stock MIUI

Both does not work =(

I have no idea what's wrong, according to packet sniffer Android sends mDNS request and `external-mdns` replies to it, everything looks correct, however no luck.

------

<details>
<summary>mdns.yaml</summary>

```
kind: Namespace
apiVersion: v1
metadata:
  name: kube-mdns
  labels:
    k8s-app: mdns
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mdns
  namespace: kube-mdns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mdns
  namespace: kube-mdns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "watch"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mdns-viewer
  namespace: kube-mdns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mdns
subjects:
- kind: ServiceAccount
  name: mdns
  namespace: kube-mdns
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mdns
  namespace: kube-mdns
spec:
  selector:
    matchLabels:
      app: mdns
  template:
    metadata:
      labels:
        app: mdns
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
      serviceAccountName: mdns
      hostNetwork: true
      containers:
      - name: mdns
        image: 192.168.89.2:5000/external-mdns:latest
        args:
        - -source=service
        - -source=ingress
        - -expose-ipv6=true
        - -without-namespace=true
        ports:
          - containerPort: 5353
            protocol: UDP
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          privileged: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BROADCAST
```
</details>

<details>
<summary>kubectl get pods,svc,pvc,deploy,daemonsets -o wide -n kube-mdns</summary>

```
NAME             READY   STATUS    RESTARTS   AGE     IP               NODE        NOMINATED NODE   READINESS GATES
pod/mdns-cqjqc   1/1     Running   0          9m33s   192.168.88.89    steamlink   <none>           <none>
pod/mdns-fpx8f   1/1     Running   0          9m33s   192.168.88.88    storage     <none>           <none>
pod/mdns-nt497   1/1     Running   0          9m33s   192.168.88.100   zoidberg    <none>           <none>

NAME                  DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE    CONTAINERS   IMAGES                                    SELECTOR
daemonset.apps/mdns   3         3         3       3            3           <none>          4d4h   mdns         192.168.89.2:5000/external-mdns:lastest   app=mdns
```
</details>

CAP file: [android-dns-mdns-wsdd-llmnr.zip](https://github.com/blake/external-mdns/files/12507203/android-dns-mdns-wsdd-llmnr.zip)
